server:
  port: 8010

spring:
  cloud:
    gateway:
      routes:
      - id: accountModule
        uri: http://localhost:8098/
        predicates:
        - Path=/accounts/**
      - id: loanModule
        uri: http://localhost:8099/
        predicates:
        - Path=/loans/**
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/employees/** 
      - id: userModule
        uri: http://localhost:8101/
        predicates:
        - Path=/users/**
        
